### ISSUE TITLE
Doesn't work with client 1.12

### ISSUE THREAD

**Issue by sigvartmh** [cnlohr/avrcraft#1]
Internal Exception io.netty.handler.codec.DecodeException
java.IOException: Packet 0/74 (kr) was larger than I expected found 33 bytes extra whilst reading packet 74.

**Comment by cnlohr** [comment]
Try the newest version of Minecraft.  I just updated everything a month or two ago.

**Comment by H3wastooshort** [comment]
use MC1.8!

**Comment by cnlohr** [comment]
Did you see if this works with that?  Also, what is the newest?

**Comment by sigvartmh** [comment]
Works with older clients I'll just close this 👍

**Comment by cnlohr** [comment]
I am really curious how the protocol has changed, and what it would take to support the newer clients.

**Comment by H3wastooshort** [comment]
good idea

**Comment by cnlohr** [comment]
I would really appreciate it if someone could work through and update this project, as I periodically have need for it.

The general idea is you connect a client, see where it breaks, and move from there fixing stuff.

Wireshark is usually pretty helpful, along with throwing in mountains of prinf()'s :-D

**Comment by sigvartmh** [comment]
I'll try to see if I have time this week to look at it ^-^.
Tried once before but didn't get very far but then again didn't set up Wireshark

Any suggestion where to look at the client connection in the code?
From what i remember the handshaking was an issue https://wiki.vg/Protocol#Handshaking maybe also the encryption step but I wonder if that could be disabled.

**Comment by cnlohr** [comment]
I would definitely try wireshark first, to get a feel for what exactly each side is sending back and forth.  From what I remember, though, encryption has always been optional.

**Comment by cnlohr** [comment]
Going back a step... what older version did you get to work with this?  I would like to confirm operation myself, but I can't seem to get any of the specific versions to fire up.  I would like to update the readme at the very least.

**Comment by cnlohr** [comment]
Interesting, I don't see anything wrong with 1.11.2 when I use it, I wonder what the problems were...

**Comment by sigvartmh** [comment]
Took two captures of one success and one failure so far, haven't really went into it i'll find a minecraft disector to have a look at the packages.


[wirecap.zip](https://github.com/cnlohr/avrcraft/files/2687954/wirecap.zip)

**Comment by cnlohr** [comment]
I'm actually working on 1.13.2 right now... https://github.com/cnlohr/avrcraft/tree/attempt_at_13_2

It looks like the major difference is that you _must_ use palettes, which is actually pretty ok and kind of convenient.  

There were a number of problems so far...

Also, I think it's possible to get rid of the baked gzip map start data... This would be a pretty cool boon, and allow easy loading/unloading of chunks arbitrarily, instead of being limited to one chunk like we currently are.

**Comment by Mhowser** [comment]
Any possibility this project could be updated to 1.16?

**Comment by cnlohr** [comment]
I have tried several times... The short answer is "no"... But conveniently, Minecraft has made it very easy to launch old versions!!!  I just tested this two nights ago and it worked like a charm!

**Comment by ElectronicsBoy** [comment]
> I have tried several times... The short answer is "no"... But conveniently, Minecraft has made it very easy to launch old versions!!! I just tested this two nights ago and it worked like a charm!

Hey, i would suggest to just make it cracked, from 1.12 (i think) they added encryption for non-cracked servers and no encryption for cracked server, i would suggest to try this once..
