### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jshin313** [cnlohr/avrcraft#2]
Hello. What are the limitations for using your code (attribution? commercial use? modification? etc.) Do you have a specific license or something? Thanks.

**Comment by cnlohr** [comment]
Oh weird, I thought I commented on this a while ago.  Answer is all code in this repo is freely licensable under the MIT/x11 or NewBSD licenses.  They should be compatible with anything you want to do.  Basically, you can sell it, just in the original code, you need to keep credit.

**Comment by jshin313** [comment]
Thanks!
