### ISSUE TITLE
How to uploade the code? from the esp8266 folder

### ISSUE THREAD

**Issue by ghost** [cnlohr/avrcraft#3]
How to uploade the code?
How to uploade the code?
How to uploade the code?
How to uploade the code?
How to uploade the code?
How to uploade the code?
How to uploade the code?
How to uploade the code?
How to uploade the code?
How to upl

**Comment by cnlohr** [comment]
Follow the instructions on esp82xx and in the esp8266 folder, say `make burn`

**Comment by ghost** [comment]
can you make a video on that?
i cant understand.
